services:
#    parcel.example:
#        class: ParcelBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
parameters:
    parcel_rest.parcel.class: ParcelBundle\Entity\Parcel
services:
    parcel_rest.parcel_form.handler:
        class: ParcelBundle\Handler\ParcelFormHandler
        arguments:   ['@doctrine.orm.entity_manager',   %parcel_rest.parcel.class%, '@form.factory', 'ParcelBundle\Form\ParcelType']